services:
  seanime:
    image: umagistr/seanime:latest
    container_name: seanime
    environment:
      - SEANIME_SERVER_HOST=0.0.0.0
      - SEANIME_SERVER_PORT=43211
    ports:
      - "3211:43211"
    volumes:
      - ./seanime-config:/root/.config/Seanime
      - ./anime:/anime
      - ./downloads:/downloads
    restart: unless-stopped
